#!/bin/sh

echo "Running check..."

# Validate code
./gradlew check

status=$?

if [ "$status" = 0 ] ; then
    echo "Validation found no issues. Proceeding with commit."
    exit 0
else
    echo 1>&2 "Validation found issues you need to fix before commit."
    exit 1
fi
